class Level:
    string_representation3 = [
        "PPPPPPPPPPPPPPPPPPPP",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "P                  P",
        "PPPPPPPPPPPPPPPPPPPP", ]

    string_representation = [
        "PPPPPPPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPP PPPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPPPPPP", ]

    string_representation2 = [
        "PPPPPPPPPPPPPPPPPPPP",
        "P                  P",
        "P        P PP PPP  P",
        "P         P  PPPP  P",
        "P         P   PPP  P",
        "P                  P",
        "P  P   PPPPPP   P  P",
        "P  P   P    P   P  P",
        "P  P   P    P   P  P",
        "P  P   PP  PP   P  P",
        "P                  P",
        "PPP    P P         P",
        "PPP P    PP P  P   P",
        "PPP PP   PP P  P   P",
        "PPP  PPPPPP PPP    P",
        "PPPP        PPP    P",
        "PPPP        PPP    P",
        "PPPPPPPPPPPPPPPPPPPP", ]